<?php

/**
 * Implement hook_enable()
 */
function classified_enable() {
  drupal_set_message($message = t("The classified  module was successfully enabled. Set the level of classification for your site on the <a href=../settings/classified>Classified Administration page.</a>"), $type = 'status');
  variable_set('classified_level', '0');
}

/**
 * Implement hook_disble()
 */
  function classified_disable() {
    drupal_set_message($message = t('The classified module was successfully disabled.'), $type = 'status');
}


/**
 * Implement hook_help()
 */
function classified_help($path, $arg) {
  switch ($path) {
    case 'admin/help#classified':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("The classified Module places a colored banner indicating the DoD level of classification for the site.") . '<p>';
      return $output;
  }
}

/**
 * Implement hook_permissions
 */
function classified_perm() {
  return array('administer classified');
}


/**
 * Implement hook_init().
 */
function classified_init() {
  if (!user_access('access content')) {
    return;
  }
  //drupal_add_css($path .'/classified.css', array('preprocess' => FALSE));
  
/*
  $alert_msg = "Hi there from php variable";
  drupal_add_js(array('classifiedModule_settings' => array('alert_msg' => $alert_msg)), 'setting');

  //add your modules Javascript file
  drupal_add_js(drupal_get_path('module', 'classified') .'/classified.js');
  */
  $level = variable_get('classification_level', '0');
  drupal_set_message('Classificaiton level is '. $level);





}

/**
 * Implement hook_menu()
 */
function classified_menu() {
  $items['admin/settings/classified'] = array(
    'title' => 'Classified Settings',
    'description' => 'Adjust settings for the classified module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('classified_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Module settings form.
 */
function classified_settings() { 
  $form['help'] = array(
    '#type' => 'markup',
    '#value' => t('Select the level of <em>Classification</em> for this site:'),
    '#weight' => -1,
  );

  $form['classified_level'] = array(
    '#type' => 'radios',
    '#title' => t('Classification Level'),
    '#description' => t('Select the Classification Level for your site.'),
    '#default_value' => t('Unclassified'),
    '#options' => array(t('Unclassified'), t('Classified'), t('Top-Secret')),
    '#description' => t('Select the Classification Level.'),
  );
  return system_settings_form($form);
}


function classified_level_submit($form, &$form_state) {
    $token = $form['classified_level']['#value'];
    $form_state['values']['classified_level'] = $token;
    variable_set('classified_level', check_plain($token));
}


/*

function classified_variable_set($name, $value) {
  $name = "classified_level";
  $value = 1;
}


function classified_form_submit($form, &$form_state) {
  $classified_level = check_plain($form_state['values']['user_message']);
  //just doing a quick variable set to store the string.
  variable_set('classification_level', $user_msg);


*/



